In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[1.0194e-38, 1.0469e-38, 1.0010e-38],
        [5.9694e-39, 8.9082e-39, 1.0194e-38],
        [9.1837e-39, 8.4490e-39, 1.0102e-38],
        [1.0561e-38, 1.0286e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 9.9184e-39]])


In [5]:
x = torch.rand(5, 3, dtype = torch.float)
print(x)

tensor([[0.8333, 0.0951, 0.1852],
        [0.7086, 0.5424, 0.2458],
        [0.3577, 0.6074, 0.9924],
        [0.6241, 0.6998, 0.4687],
        [0.3324, 0.4525, 0.3729]])


In [7]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [9]:
x = torch.eye(2)
x

tensor([[1., 0.],
        [0., 1.]])

# 创建Tensor

还有很多函数可以创建Tensor 下表给了一些常用的作参考。
|函数|功能|
|-|-|
|Tensor(*sizes)|基础构造函数|
|tensor(data,)|类似np.array的构造函数|
ones(*sizes)|全1Tensor|
zeros(*sizes)|全0Tensor|
eye(*sizes)|对角线为1，其他为0|
arange(s,e,step)|从s到e，步长为step|
linspace(s,e,steps)|从s到e，均匀切分成steps份|
rand/randn(*sizes)|均匀/标准分布|
normal(mean,std)/uniform(from,to)|正态分布/均匀分布|
randperm(m)|随机排列|

# Tensor 操作
## add 加法

In [18]:

y = torch.rand(5,3)
x = torch.rand_like(y)
result = torch.empty_like(x)
# 以下结果一样
print(x+y)
print(torch.add(x,y, out = result))
print(torch.add(x,y))
print(y.add_(x))

tensor([[1.3269, 1.1801, 0.3466],
        [0.4613, 1.1349, 1.3016],
        [0.7931, 1.0928, 0.7092],
        [0.4618, 0.8427, 0.7418],
        [1.3288, 1.0113, 0.8561]])
tensor([[1.3269, 1.1801, 0.3466],
        [0.4613, 1.1349, 1.3016],
        [0.7931, 1.0928, 0.7092],
        [0.4618, 0.8427, 0.7418],
        [1.3288, 1.0113, 0.8561]])
tensor([[1.3269, 1.1801, 0.3466],
        [0.4613, 1.1349, 1.3016],
        [0.7931, 1.0928, 0.7092],
        [0.4618, 0.8427, 0.7418],
        [1.3288, 1.0113, 0.8561]])
tensor([[1.3269, 1.1801, 0.3466],
        [0.4613, 1.1349, 1.3016],
        [0.7931, 1.0928, 0.7092],
        [0.4618, 0.8427, 0.7418],
        [1.3288, 1.0113, 0.8561]])


## Index 索引

In [20]:
y = x[0,:]
y += 1
print(y)
print(x[0,:]) # 源tensor也被改了

tensor([2.4390, 2.2944, 2.0133])
tensor([2.4390, 2.2944, 2.0133])


## 改变形状
使用 `view()` 来改变 `Tensor` 的形状.

In [22]:
y = x.view(15)
z = x.view(-1,5)
print(x.size(),y.size(),z.size())
# 注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


## 深拷贝

In [23]:
## 深拷贝
# 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。
x_cp = x.clone().view(15)
x -= 1
print(x,x_cp)

tensor([[ 1.4390,  1.2944,  1.0133],
        [-0.5535, -0.5277, -0.3763],
        [-0.5796, -0.2666, -0.6799],
        [-0.7687, -0.9689, -0.6346],
        [-0.5383, -0.5731, -0.4967]]) tensor([2.4390, 2.2944, 2.0133, 0.4465, 0.4723, 0.6237, 0.4204, 0.7334, 0.3201,
        0.2313, 0.0311, 0.3654, 0.4617, 0.4269, 0.5033])


In [25]:
# item()
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.6987])
-1.6987019777297974


# 线性代数

PyTorch中的Tensor支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等等，可参考官方文档。

# tensor 和 numpy

In [26]:
a = torch.ones(5)
b = a.numpy()
print(a, b)
a += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
a +=1 
print(a,b)
b+= 1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
