In [2]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [5]:
import torch
import torch.nn as nn
loss = nn.L1Loss()
input = torch.randn(3,5, requires_grad = True)
target = torch.randn(3,5)
output = loss(input, target)
output.backward()
print(f'{input}\n{output}\n{target}')

tensor([[ 0.0115,  1.5342, -0.3544, -0.9033,  2.0170],
        [-0.4587, -0.5162,  0.0995, -1.4177, -1.0563],
        [ 0.6875, -0.2983, -0.9317,  0.7087,  0.3659]], requires_grad=True)
0.8582696318626404
tensor([[ 0.6277,  1.0849,  0.4288,  0.3152,  1.2625],
        [ 0.9532, -0.5183, -0.8018,  0.0844, -1.4761],
        [-1.2028, -1.1908, -0.8288, -1.0176,  0.1629]])


In [8]:
import torch
x = torch.ones(5)
w = torch.randn(5,3,requires_grad=True)
b = torch.randn(3, requires_grad=True)
y = torch.zeros(3)
z = torch.matmul(x,w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [9]:
print('Gradient function for z =',z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x000002761E74A1C0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000002761E74AC70>


In [10]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0039, 0.1249, 0.2577],
        [0.0039, 0.1249, 0.2577],
        [0.0039, 0.1249, 0.2577],
        [0.0039, 0.1249, 0.2577],
        [0.0039, 0.1249, 0.2577]])
tensor([0.0039, 0.1249, 0.2577])


In [11]:
z = torch.matmul(x,w) + b
print(z.requires_grad)
with torch.no_grad():
    z = torch.matmul(x,w) + b
print(z.requires_grad)



True
False
